disable desktop and iOS tests until they actually work

diff --git a/.github/workflows/flutter_integration_testing.yml b/.github/workflows/flutter_integration_testing.yml
--- a/.github/workflows/flutter_integration_testing.yml
+++ b/.github/workflows/flutter_integration_testing.yml
@@ -41,268 +41,267 @@ jobs:
           prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
           prLabels: ${{ steps.PR.outputs.pr_labels }}
           contains: ${{ contains(steps.PR.outputs.pr_labels, 'ci-test-ui') }}
+  # flutter-desktop:
+  #   runs-on: ubuntu-latest
+  #   name: Flutter Desktop
+  #   continue-on-error: true
+  #   needs:
+  #    - run_checker
      
-  flutter-desktop:
-    runs-on: ubuntu-latest
-    name: Flutter Desktop
-    continue-on-error: true
-    needs:
-     - run_checker
-     
-    if: ${{ github.ref == 'refs/heads/main' || needs.run_checker.outputs.should_run_all != 'false' || needs.run_checker.outputs.should_run_desktop != 'false' }}
+  #   if: ${{ github.ref == 'refs/heads/main' || needs.run_checker.outputs.should_run_all != 'false' || needs.run_checker.outputs.should_run_desktop != 'false' }}
 
-    steps:
-      - uses: actions/checkout@v2
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Install extra deps
-        run: |
-          sudo apt-get update -y
-          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev
-          sudo apt install -y dbus-x11 network-manager upower mpv libmpv-dev
+  #     - name: Install extra deps
+  #       run: |
+  #         sudo apt-get update -y
+  #         sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev
+  #         sudo apt install -y dbus-x11 network-manager upower mpv libmpv-dev
 
-      - name: Install supported toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: nightly
-          override: true
+  #     - name: Install supported toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: nightly
+  #         override: true
 
-      - uses: Swatinem/rust-cache@v1
+  #     - uses: Swatinem/rust-cache@v1
 
-      - name: Install cargo-make
-        uses: davidB/rust-cargo-make@v1
+  #     - name: Install cargo-make
+  #       uses: davidB/rust-cargo-make@v1
 
-      - uses: subosito/flutter-action@v2
-        name: Set up flutter
-        with:
-          flutter-version: '3.22'
-          channel: 'stable'
+  #     - uses: subosito/flutter-action@v2
+  #       name: Set up flutter
+  #       with:
+  #         flutter-version: '3.22'
+  #         channel: 'stable'
 
-      - uses: actions/setup-python@v4
-        with:
-          python-version: 3.8
+  #     - uses: actions/setup-python@v4
+  #       with:
+  #         python-version: 3.8
 
-      - uses: michaelkaye/setup-matrix-synapse@main
-        with:
-          installer: poetry
-          uploadLogs: true
-          httpPort: 8118
-          disableRateLimiting: true
-          customModules: synapse_super_invites
-          customConfig: |
-            modules:
-              - module: "synapse_super_invites.SynapseSuperInvites"
-                config:
-                  sql_url: "sqlite://"
-                  generate_registration_token: true
+  #     - uses: michaelkaye/setup-matrix-synapse@main
+  #       with:
+  #         installer: poetry
+  #         uploadLogs: true
+  #         httpPort: 8118
+  #         disableRateLimiting: true
+  #         customModules: synapse_super_invites
+  #         customConfig: |
+  #           modules:
+  #             - module: "synapse_super_invites.SynapseSuperInvites"
+  #               config:
+  #                 sql_url: "sqlite://"
+  #                 generate_registration_token: true
 
-      - name: Install & Run MailHog
-        run: |
-          wget -q https://github.com/mailhog/MailHog/releases/download/v1.0.1/MailHog_linux_amd64
-          sudo chmod +x MailHog_linux_amd64
-          ./MailHog_linux_amd64 &
+  #     - name: Install & Run MailHog
+  #       run: |
+  #         wget -q https://github.com/mailhog/MailHog/releases/download/v1.0.1/MailHog_linux_amd64
+  #         sudo chmod +x MailHog_linux_amd64
+  #         ./MailHog_linux_amd64 &
 
-      - name: Enable Linux Desktop
-        run: flutter config --enable-linux-desktop
+  #     - name: Enable Linux Desktop
+  #       run: flutter config --enable-linux-desktop
 
-      - name: Build Native
-        run: cargo make desktop
+  #     - name: Build Native
+  #       run: cargo make desktop
 
-      - name: Flutter setup
-        working-directory: app
-        run: flutter pub get
+  #     - name: Flutter setup
+  #       working-directory: app
+  #       run: flutter pub get
 
-      - name: Open Keyring
-        uses: t1m0thyj/unlock-keyring@v1
+  #     - name: Open Keyring
+  #       uses: t1m0thyj/unlock-keyring@v1
 
-      - name: Run flutter integration tests
-        working-directory: app
-        run: |
-          export DISPLAY=:99
-          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
-          xvfb_pid=$!
-          flutter run integration_test/main_test.dart  \
-              -d linux \
-              --hot \
-              --host-vmservice-port 9753 \
-              --disable-service-auth-codes \
-              --dart-define CI=true \
-              --dart-define CONVENIENT_TEST_APP_CODE_DIR=lib \
-              --dart-define DEFAULT_HOMESERVER_URL=http://localhost:8118/ \
-              --dart-define DEFAULT_HOMESERVER_NAME=localhost \
-              --dart-define RAGESHAKE_URL=http://localhost:9110/api/submit \
-              --dart-define MAILHOG_URL=http://localhost:8025 \
-              --dart-define RAGESHAKE_LISTING_URL=http://localhost:9110/api/listing \
-              --dart-define DEFAULT_HOMESERVER_URL=http://localhost:8118 \
-              --dart-define DEFAULT_HOMESERVER_NAME=localhost \
-              &
-          subscript_pid=$!
+  #     - name: Run flutter integration tests
+  #       working-directory: app
+  #       run: |
+  #         export DISPLAY=:99
+  #         sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
+  #         xvfb_pid=$!
+  #         flutter run integration_test/main_test.dart  \
+  #             -d linux \
+  #             --hot \
+  #             --host-vmservice-port 9753 \
+  #             --disable-service-auth-codes \
+  #             --dart-define CI=true \
+  #             --dart-define CONVENIENT_TEST_APP_CODE_DIR=lib \
+  #             --dart-define DEFAULT_HOMESERVER_URL=http://localhost:8118/ \
+  #             --dart-define DEFAULT_HOMESERVER_NAME=localhost \
+  #             --dart-define RAGESHAKE_URL=http://localhost:9110/api/submit \
+  #             --dart-define MAILHOG_URL=http://localhost:8025 \
+  #             --dart-define RAGESHAKE_LISTING_URL=http://localhost:9110/api/listing \
+  #             --dart-define DEFAULT_HOMESERVER_URL=http://localhost:8118 \
+  #             --dart-define DEFAULT_HOMESERVER_NAME=localhost \
+  #             &
+  #         subscript_pid=$!
 
-          # actual manager runner
-          dart run convenient_test_manager_dart --enable-report-saver
-          exit_status=$?
-          kill "$xvfb_pid" "$subscript_pid"
-          exit exit_status
+  #         # actual manager runner
+  #         dart run convenient_test_manager_dart --enable-report-saver
+  #         exit_status=$?
+  #         kill "$xvfb_pid" "$subscript_pid"
+  #         exit exit_status
 
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v1
-        if: failure()
-        with:
-          name: linux-desktop-convtest-report
-          path: /tmp/ConvenientTest/
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v1
+  #       if: failure()
+  #       with:
+  #         name: linux-desktop-convtest-report
+  #         path: /tmp/ConvenientTest/
 
-      # file an error if this failed on `main` post-merge
-      - name: Report issue
-        if: ${{ github.ref == 'refs/heads/main' && failure() }}
-        uses: JasonEtco/create-an-issue@v2
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-          TITLE: "Desktop integration tests failed on main"
-          FAILED_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
-          ARTIFACT_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        with:
-          assignees: gnunicorn
-          filename: .github/templates/failure-report-template.md.tmpl
-          update_existing: true
+  #     # file an error if this failed on `main` post-merge
+  #     - name: Report issue
+  #       if: ${{ github.ref == 'refs/heads/main' && failure() }}
+  #       uses: JasonEtco/create-an-issue@v2
+  #       env:
+  #         GITHUB_TOKEN: ${{ github.token }}
+  #         TITLE: "Desktop integration tests failed on main"
+  #         FAILED_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
+  #         ARTIFACT_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #       with:
+  #         assignees: gnunicorn
+  #         filename: .github/templates/failure-report-template.md.tmpl
+  #         update_existing: true
 
-  flutter-ios:
-    runs-on: macos-latest
-    environment: release
+  # flutter-ios:
+  #   runs-on: macos-latest
+  #   environment: release
 
-    name: iOS
-    needs:
-     - run_checker
-    if: ${{ github.ref == 'refs/heads/main' || needs.run_checker.outputs.should_run_ios != 'false' || needs.run_checker.outputs.should_run_emulator != 'false' || needs.run_checker.outputs.should_run_all != 'false' }}
-    continue-on-error: true
-    steps:
-      - uses: actions/checkout@v2
+  #   name: iOS
+  #   needs:
+  #    - run_checker
+  #   if: ${{ github.ref == 'refs/heads/main' || needs.run_checker.outputs.should_run_ios != 'false' || needs.run_checker.outputs.should_run_emulator != 'false' || needs.run_checker.outputs.should_run_all != 'false' }}
+  #   continue-on-error: true
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Install supported toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: nightly
-          override: true
+  #     - name: Install supported toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: nightly
+  #         override: true
 
-      - uses: Swatinem/rust-cache@v1
+  #     - uses: Swatinem/rust-cache@v1
 
-      - name: Install cargo-make
-        uses: davidB/rust-cargo-make@v1
+  #     - name: Install cargo-make
+  #       uses: davidB/rust-cargo-make@v1
 
-      - name: Rust iOS Setup
-        run: cargo make setup-ios
+  #     - name: Rust iOS Setup
+  #       run: cargo make setup-ios
 
-      - name: Unlock git-crypt
-        run: |
-          brew install git-crypt
-          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 --decode > .github/assets/git-crypt-key
-          git-crypt unlock .github/assets/git-crypt-key
-          echo "Files found:"
-          git-crypt status -e
+  #     - name: Unlock git-crypt
+  #       run: |
+  #         brew install git-crypt
+  #         echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 --decode > .github/assets/git-crypt-key
+  #         git-crypt unlock .github/assets/git-crypt-key
+  #         echo "Files found:"
+  #         git-crypt status -e
 
-      # Install the Apple certificate and provisioning profile
-      - name: Install the Apple certificates
-        env:
-          P12_PASSWORD: ${{ secrets.BUILD_CERTS_P12_PASSWORD }}
-          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-        run: |
-          echo "starting in $RUNNER_TEMP"
-          # create variables
-          CERTIFICATE_PATH=".github/assets/build_certificates.p12"
-          KEYCHAIN_PATH="$RUNNER_TEMP/app-signing.keychain-db"
-          echo "vars set"
-          # import certificate and provisioning profile from secrets
-          # create temporary keychain
-          echo "creating keychain"
-          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
-          echo "setting keychain"
-          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
-          echo "unlocking keychain"
-          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
-          # import certificate to keychain
-          echo "importing certificate"
-          security import "$CERTIFICATE_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
-          echo "listing keychains"
-          security list-keychain -d user -s "$KEYCHAIN_PATH"
-      - name: Install the Apple provisioning profile
-        run: |
-          echo "Installing provision profiles"
-          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
-          cp .github/assets/provision_profiles/* ~/Library/MobileDevice/Provisioning\ Profiles/
-          ls -ltas ~/Library/MobileDevice/Provisioning\ Profiles/
+  #     # Install the Apple certificate and provisioning profile
+  #     - name: Install the Apple certificates
+  #       env:
+  #         P12_PASSWORD: ${{ secrets.BUILD_CERTS_P12_PASSWORD }}
+  #         KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+  #       run: |
+  #         echo "starting in $RUNNER_TEMP"
+  #         # create variables
+  #         CERTIFICATE_PATH=".github/assets/build_certificates.p12"
+  #         KEYCHAIN_PATH="$RUNNER_TEMP/app-signing.keychain-db"
+  #         echo "vars set"
+  #         # import certificate and provisioning profile from secrets
+  #         # create temporary keychain
+  #         echo "creating keychain"
+  #         security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
+  #         echo "setting keychain"
+  #         security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
+  #         echo "unlocking keychain"
+  #         security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
+  #         # import certificate to keychain
+  #         echo "importing certificate"
+  #         security import "$CERTIFICATE_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
+  #         echo "listing keychains"
+  #         security list-keychain -d user -s "$KEYCHAIN_PATH"
+  #     - name: Install the Apple provisioning profile
+  #       run: |
+  #         echo "Installing provision profiles"
+  #         mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
+  #         cp .github/assets/provision_profiles/* ~/Library/MobileDevice/Provisioning\ Profiles/
+  #         ls -ltas ~/Library/MobileDevice/Provisioning\ Profiles/
 
-      - uses: subosito/flutter-action@v2
-        name: Set up flutter
-        with:
-          flutter-version: '3.22'
-          channel: 'stable'
+  #     - uses: subosito/flutter-action@v2
+  #       name: Set up flutter
+  #       with:
+  #         flutter-version: '3.22'
+  #         channel: 'stable'
 
-      - uses: actions/setup-python@v4
-        with:
-          python-version: 3.8
+  #     - uses: actions/setup-python@v4
+  #       with:
+  #         python-version: 3.8
 
-      - uses: michaelkaye/setup-matrix-synapse@main
-        with:
-          uploadLogs: true
-          httpPort: 8118
-          disableRateLimiting: true
-          customModules: synapse_super_invites
-          customConfig: |
-            modules:
-              - module: "synapse_super_invites.SynapseSuperInvites"
-                config:
-                  sql_url: "sqlite://"
-                  generate_registration_token: true
+  #     - uses: michaelkaye/setup-matrix-synapse@main
+  #       with:
+  #         uploadLogs: true
+  #         httpPort: 8118
+  #         disableRateLimiting: true
+  #         customModules: synapse_super_invites
+  #         customConfig: |
+  #           modules:
+  #             - module: "synapse_super_invites.SynapseSuperInvites"
+  #               config:
+  #                 sql_url: "sqlite://"
+  #                 generate_registration_token: true
 
-      - name: Install & Run MailHog
-        run: |
-          wget -q https://github.com/mailhog/MailHog/releases/download/v1.0.1/MailHog_linux_amd64
-          sudo chmod +x MailHog_linux_amd64
-          ./MailHog_linux_amd64 &
+  #     - name: Install & Run MailHog
+  #       run: |
+  #         wget -q https://github.com/mailhog/MailHog/releases/download/v1.0.1/MailHog_linux_amd64
+  #         sudo chmod +x MailHog_linux_amd64
+  #         ./MailHog_linux_amd64 &
 
-      - name: Build Native
-        run: cargo make --profile release ios-sim
+  #     - name: Build Native
+  #       run: cargo make --profile release ios-sim
  
-      - uses: futureware-tech/simulator-action@v3
-        id: ios_simulator
-        timeout-minutes: 30
-        with:
-          model: 'iPhone 14'
+  #     - uses: futureware-tech/simulator-action@v3
+  #       id: ios_simulator
+  #       timeout-minutes: 30
+  #       with:
+  #         model: 'iPhone 14'
 
-      - name: Flutter setup
-        working-directory: app
-        run: |
-          flutter pub get
+  #     - name: Flutter setup
+  #       working-directory: app
+  #       run: |
+  #         flutter pub get
 
-      - name: Run flutter integration tests
-        timeout-minutes: 30
-        run: .github/scripts/flutter-integration-tests.sh
+  #     - name: Run flutter integration tests
+  #       timeout-minutes: 30
+  #       run: .github/scripts/flutter-integration-tests.sh
 
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v1
-        if: failure()
-        with:
-          name: ios-convtest-report
-          path: /tmp/ConvenientTest/
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v1
+  #       if: failure()
+  #       with:
+  #         name: ios-convtest-report
+  #         path: /tmp/ConvenientTest/
 
-      # file an error if this failed on `main` post-merge
-      - name: Report issue
-        if: ${{ github.ref == 'refs/heads/main' && failure() }}
-        uses: JasonEtco/create-an-issue@v2
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-          TITLE: "iOS integration tests failed on main"
-          FAILED_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
-          ARTIFACT_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        with:
-          assignees: gnunicorn
-          filename: .github/templates/failure-report-template.md.tmpl
-          update_existing: true
+  #     # file an error if this failed on `main` post-merge
+  #     - name: Report issue
+  #       if: ${{ github.ref == 'refs/heads/main' && failure() }}
+  #       uses: JasonEtco/create-an-issue@v2
+  #       env:
+  #         GITHUB_TOKEN: ${{ github.token }}
+  #         TITLE: "iOS integration tests failed on main"
+  #         FAILED_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
+  #         ARTIFACT_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #       with:
+  #         assignees: gnunicorn
+  #         filename: .github/templates/failure-report-template.md.tmpl
+  #         update_existing: true
 
-      - name: Clean up keychain and provisioning profile
-        if: ${{ always() }}
-        run: |
-          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
-          rm ~/Library/MobileDevice/Provisioning\ Profiles/*
-          rm .github/assets/git-crypt-key
+  #     - name: Clean up keychain and provisioning profile
+  #       if: ${{ always() }}
+  #       run: |
+  #         security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
+  #         rm ~/Library/MobileDevice/Provisioning\ Profiles/*
+  #         rm .github/assets/git-crypt-key
 
   flutter-android:
     runs-on: ubuntu-latest
